version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    restart: always
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dynamic:/dynamic
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --providers.file.directory=/dynamic
      - --providers.file.watch=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.address=:80
      - --log.level=INFO
    labels:
      - 'traefik.enable=true'
      # Global HTTP -> HTTPS redirection
      - 'traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.http-catchall.entrypoints=web'
      - 'traefik.http.routers.http-catchall.middlewares=redirect-to-https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'

networks:
  web:
    external: true
